# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/sergi/project_mips/project_mips.cache/wt [current_project]
set_property parent.project_path C:/Users/sergi/project_mips/project_mips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/sergi/project_mips/project_mips.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/sergi/project_mips/project_mips.srcs/sources_1/new/register_file.vhd
  C:/Users/sergi/project_mips/project_mips.srcs/sources_1/new/Instruction_Memory_VHDL.vhd
  C:/Users/sergi/project_mips/project_mips.srcs/sources_1/new/control_unit_vhdl.vhd
  C:/Users/sergi/project_mips/project_mips.srcs/sources_1/new/ALU_VHDL.vhd
  C:/Users/sergi/project_mips/project_mips.srcs/sources_1/new/ALU_Control_VHDL.vhd
  C:/Users/sergi/project_mips/project_mips.srcs/sources_1/new/Data_Memory_VHDL.vhd
  C:/Users/sergi/project_mips/project_mips.srcs/sources_1/new/test_env.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/sergi/project_mips/project_mips.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/sergi/project_mips/project_mips.srcs/constrs_1/new/constraints.xdc]


synth_design -top test_env -part xc7k70tfbv676-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
